export enum PaymentEventTypeEnum {
    INITIAL_PURCHASE = 'INITIAL_PURCHASE',
    RENEWAL = 'RENEWAL',
    EXPIRATION = 'EXPIRATION',
    TRANSFER = 'TRANSFER',
    CANCELLATION = 'CANCELLATION', // IGNORE
    BILLING_ISSUE = 'BILLING_ISSUE', // IGNORE
    SUBSCRIPTION_PAUSED = 'SUBSCRIPTION_PAUSED', // IGNORE
}
