export enum EPositionType {
    GOALKEEPER_LEGACY = 'Goalkeeper',
    CENTER_BACK_LEGACY = 'Center Back',
    CENTER_MID_LEGACY = 'Center Mid',
    FORWARD_LEGACY = 'Forward',
    OUTSIDE_MID_LEGACY = 'Outside Mid',
    OUTSIDE_BACK_LEGACY = 'Outside Back',
    GOALKEEPER = 'Goalkeeper (GK)',
    RIGHT_FULLBACK = 'Right Fullback (RB)',
    LEFT_FULLBACK = 'Left Fullback (LB)',
    CENTER_BACK = 'Center Back (CB)',
    SWEEPER = 'Sweeper (SW)',
    DEFENSIVE_MID = 'Defensive Midfielder (CDM)',
    RIGHT_MID = 'Right Midfielder/Winger (RM/RW)',
    CENTER_MID = 'Central Midfielder (CM)',
    ATTACKING_MID = 'Attacking Midfielder (CAM)',
    LEFT_MID = 'Left Midfielder/Winger (LM/LW)',
    STRIKER = 'Striker (ST)',
    SECOND_STRIKER = 'Second Striker/Playmaker',
    WINGER = 'Winger (RW/LW)',
    WINGBACK = 'Wingback (WB)',
    FALSE = 'False 9',
    INSIDE_FORWARDS = 'Inside Forwards (IF)',
}
